baseURL: https://az-qianchen.github.io/Tuclink/ # 基础链接（测试无效）
defaultContentLanguage: zh # 默认语言
defaultContentLanguageInSubdir: true # 多语言文件夹
translationKey: about

languages: # 翻译
#   zh:
#     baseURL: https://tuclink.com/zh/
#     contentDir: content/zh
#     languageName: Chinese
#     weight: 1
#   en:
#     baseURL: https://tuclink.com/en/
#     contentDir: content/en
#     languageName: English
#     weight: 2
  zh:
    contentDir: content/zh
    languageName: "Chinese"
    weight: 1
    # taxonomies:
    #   category: categories
    #   tag: tags
    #   series: series
    menu:
      main:
        - name: 文章
          url: /archives/
          weight: 5
        - name: 搜索
          url: /search/
          weight: 10
        - name: 标签
          url: /tags/
          weight: 15
        - name: 列表
          url: /post/
          weight: 20
  en:
    contentDir: content/en
    languageName: "English"
    weight: 2
    # taxonomies:
    #   category: categories
    #   tag: tags
    #   series: series
    menu:
      main:
        - name: Archive
          url: /archives/
          weight: 5
        - name: Search
          url: /search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 15
        - name: List
          url: /post/
          weight: 20

title: 突触递质 # 网站名称
# paginate: 5
theme: PaperMod # 主题
unsafe: true
# 网站生成配置
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# 启用谷歌网站分析
# googleAnalytics: UA-123-45

# 启用压缩
minify:
  disableXML: true
  minifyOutput: true

# 文章默认配置
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 突触递质
  description: "飘渺的想法，和未尽的梦"
  keywords: [Blog, Portfolio, PaperMod]
  author: QianChen # 默认作者
  # images: ["https://s2.loli.net/2024/03/07/X6w49UasreE3cvH.jpg"] # 头图
  DateFormat: "2006-1-2" # 日期格式

  defaultTheme: auto # 主题色
  disableThemeToggle: false # 禁用主题切换

  ShowBreadCrumbs: true # 面包屑导航
  ShowCodeCopyButtons: true # 是否显示代码复制按钮
  # ShowWordCount: true # 字数统计
  # ShowReadingTime: true # 阅读时间
  # ShowShareButtons: false # 分享按钮
  # ShowPostNavLinks: true # 导航链接（上下篇内容）
  # ShowRssButtonInSectionTermList: true # RSS 按钮
  # disableScrollToTop: false # 禁用回到顶部按钮
  # disableSpecial1stPost: false # 禁用第一篇文章特殊布局
  # hideSummary: false # 隐藏摘要
  # hidemeta: true # 隐藏文章数据（日期，作者）
  
  UseHugoToc: true # 目录
  ShowToc: true # 显示目录
  # TocOpen: true # 打开目录
  
  comments: true # 评论系统
  # disqusShortname: 仟尘 # Disqus 评论设置

# 网站图标
  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/ico/64.ico"
    favicon16x16: "/ico/16.ico"
    favicon32x32: "/ico/32.ico"
    apple_touch_icon: "/ico/256.ico"
    safari_pinned_tab: "/ico/64.ico"

# 首页标签
  label:
    text: "Home"
    # icon: /ico/256.ico # 头图
    iconHeight: 35

# 配置模式
  profileMode:
    enabled: flase
    title: TucLink
    subtitle: Just dream , wake or die
    imageUrl: "/ico/512.png"
    imageWidth: 300
    imageHeight: 300
    imageTitle: my image
    # buttons:
    #   - name: Posts
    #     url: /home_info

# 家庭模式
  # homeInfoParams:
  #   Title: TucLink
  #   Content: Keep Coming!

# 图标链接
  socialIcons:
    - name: twitter
      url: "https://twitter.com/Tuclink_Az"
    - name: bilibili
      url: "https://b23.tv/Dy49jbs"
    - name: reddit
      url: "https://www.reddit.com/user/Tuclink/"
    - name: youtube
      url: "https://www.youtube.com/@Tuclink"
    - name: email
      url: "mailto:feedback@tuclink.com"

# 网站分析工具
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

# 封面设置
  # cover:
    # hidden: true # 彻底隐藏
    # hiddenInList: true # 主页隐藏
    # hiddenInSingle: true # 页面隐藏
    # responsiveImages: true # 封面图片，使用快速响应图片
    # linkFullImages: true # 图片是否能跳转

# 帖子默认更改路径
  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # 更改建议
  #   appendFilePath: true # 追加文件路径

  # 搜索功能配置
  # https://www.fusejs.io/api/methods.html#search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # 返回搜索数量
    keys: ["title", "permalink", "summary", "content"]

# 暴露信息用于页面，搜索功能
outputs:
    home:
        - HTML
        - RSS
        - JSON

# 菜单
menu:
  main:
    - identifier: 文章
      name: 文章
      url: archive/
      weight: 10
    - identifier: 搜索
      name: 搜索
      url: search/
      weight: 20
    - identifier: 标签
      name: 标签
      url: tags/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma

# 代码高亮
pygmentsUseClasses: true

markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai