title: 突触递质 # 网站名称
# baseURL: https://az-qianchen.github.io/Tuclink/
baseURL: https://post.tuclink.com/ # 基础链接（测试无效）
# canonifyurls: true # 是否使用绝对路径
defaultContentLanguage: zh # 默认语言
defaultContentLanguageInSubdir: true # 多语言文件夹
translationKey: about

theme:  # 主题
  - PaperMod
  - hugo-shortcode-roneo-collection

languages: # 翻译
#   zh:
#     baseURL: https://tuclink.com/zh/
#     contentDir: content/zh
#     languageName: Chinese
#     weight: 1
#   en:
#     baseURL: https://tuclink.com/en/
#     contentDir: content/en
#     languageName: English
#     weight: 2
  zh:
    contentDir: content/zh
    languageName: "Chinese"
    weight: 1
    menu:
      main:
        - name: 文章
          url: /archives/
          weight: 5
        - name: 搜索
          url: /search/
          weight: 10
        - name: 标签
          url: /tags/
          weight: 15
        - name: 列表
          url: /post/
          weight: 20
  en:
    contentDir: content/en
    languageName: "English"
    weight: 2
    menu:
      main:
        - name: Archive
          url: /archives/
          weight: 5
        - name: Search
          url: /search/
          weight: 10
        - name: Tags
          url: /tags/
          weight: 15
        - name: List
          url: /post/
          weight: 20

paginate: 5    # 每页显示的文章数
summaryLength: 70 # 文章概览的字数，默认70

unsafe: true
# 网站生成配置
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启
buildDrafts: false
buildFuture: false
buildExpired: false


# 启用谷歌网站分析
# googleAnalytics: UA-123-45

# 启用压缩
minify:
  disableXML: true
  minifyOutput: true

# 文章默认配置
params:
  # theme params
  # DisableLanguageSwitch: true
  # TocOpen: true
  # TocSide: right
  # EnableInstantClick: false
  # EnableImageZoom: true
  # ShowShareButtons: true
  # ShareButtons:
  #   - twitter
  #   - telegram
  # ShowReadingTime: true
  # ShowWordCount: true
  # ShowCodeCopyButtons: true
  # ShowPostNavLinks: true
  # Email: hello@example.com


  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 突触递质
  description: "飘渺的想法，和未尽的梦"
  keywords: [Blog, Portfolio, PaperMod]
  author: QianChen # 默认作者
  # images: ["https://s2.loli.net/2024/03/07/X6w49UasreE3cvH.jpg"] # 头图
  DateFormat: "2006-1-2" # 日期格式

  defaultTheme: auto # 主题色
  disableThemeToggle: false # 禁用主题切换

  ShowBreadCrumbs: true # 面包屑导航
  ShowCodeCopyButtons: true # 是否显示代码复制按钮
  # ShowWordCount: true # 字数统计
  # ShowReadingTime: true # 阅读时间
  # ShowShareButtons: false # 分享按钮
  # ShowPostNavLinks: true # 导航链接（上下篇内容）
  # ShowRssButtonInSectionTermList: true # RSS 按钮
  # disableScrollToTop: false # 禁用回到顶部按钮
  # disableSpecial1stPost: false # 禁用第一篇文章特殊布局
  # hideSummary: false # 隐藏摘要
  # hidemeta: true # 隐藏文章数据（日期，作者）
  
  UseHugoToc: true # 目录
  ShowToc: true # 显示目录
  # TocOpen: true # 打开目录
  ShowLastMod: true #显示文章更新时间
  comments: true # 评论系统
  # disqusShortname: 仟尘 # Disqus 评论设置

# 网站图标
  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/ico/64.ico"
    favicon16x16: "/ico/16.ico"
    favicon32x32: "/ico/32.ico"
    apple_touch_icon: "/ico/256.ico"
    safari_pinned_tab: "/ico/64.ico"

# 首页标签
  label:
    text: "Home"
    # icon: /ico/256.ico # 头图
    iconHeight: 35

# 配置模式
  profileMode:
    enabled: flase
    title: TucLink
    subtitle: Just dream , wake or die
    imageUrl: "/ico/512.png"
    imageWidth: 300
    imageHeight: 300
    imageTitle: my image
    # buttons:
    #   - name: Posts
    #     url: /home_info

# 家庭模式
  # homeInfoParams:
  #   Title: TucLink
  #   Content: Keep Coming!

# 图标链接
  socialIcons:
    - name: bilibili
      url: "https://b23.tv/Dy49jbs"
    - name: email
      url: "mailto:feedback@tuclink.com"
    # - name: twitter
    #   url: "https://twitter.com/Tuclink_Az"
    # - name: youtube
    #   url: "https://www.youtube.com/@Tuclink"
    # - name: reddit
    #   url: "https://www.reddit.com/user/Tuclink/"

# 网站分析工具
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

# 封面设置
  cover:
    # hidden: true # 彻底隐藏
    hiddenInList: false # 主页隐藏
    hiddenInSingle: true # 页面隐藏
    responsiveImages: true # 封面图片，使用快速响应图片
    # linkFullImages: true # 图片是否能跳转

# 帖子默认更改路径
  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # 更改建议
  #   appendFilePath: true # 追加文件路径

  # 搜索功能配置
  # https://www.fusejs.io/api/methods.html#search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # 返回搜索数量
    keys: ["title", "permalink", "summary", "content"]

# 暴露信息用于页面，搜索功能
outputs:
    home:
        - HTML
        - RSS
        - JSON

# 菜单
menu:
  main:
    - identifier: 文章
      name: 文章
      url: /archive/
      weight: 10
    - identifier: 搜索
      name: 搜索
      url: /search/
      weight: 20
    - identifier: 标签
      name: 标签
      url: /tags/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma

# 代码高亮
pygmentsUseClasses: true

markup: # X
  goldmark: # X
    renderer: # X
      unsafe: true # X
  highlight:
    style: dracula # X
    lineNos: false # X
    noClasses: true # 使用 class 标签，而不是内嵌的内联样式
    codeFences: true # 代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
    guessSyntax: true # 猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
    lineNos: true # 是否显示行号
    # anchorLineNos: true
    # style: monokai
    # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
    # lineNoStart：行号从编号几开始，一般从 1 开始。
    # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.